// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POInterview.Infrastructure.Data;

#nullable disable

namespace POInterview.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250215163819_UpdateMigrationsToNewNamespaces")]
    partial class UpdateMigrationsToNewNamespaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("POInterview.Infrastructure.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("BookedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("POInterview.Infrastructure.Data.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Resource");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Resource 1",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resource 2",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resource 3",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Resource 4",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            Name = "Resource 5",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("POInterview.Infrastructure.Data.Entities.Booking", b =>
                {
                    b.HasOne("POInterview.Infrastructure.Data.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });
#pragma warning restore 612, 618
        }
    }
}
